### PR TITLE
Multilingual corpus support

### LINKED ISSUE #7: Provide support for multiple languages
Do I assume correctly in that a single corpus is only supposed to contain examples from a single language (unlike structural datasets etc)? My CLDF examples setup contains glottocodes under the column `Language_ID`, but this seems to not matter to `pyigt`. I can easily create separate example databases for each language, if that is the way to do it.

### PR DESCRIPTION
**Pull request by xrotwang**
- IGTs have now an attribute `language`
- Concordance keys are extended by this attribute

closes #7

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList as far as I can see, this should be backwards compatible.

@fmatter could you have a look at this? Concordances now have a `LANGUAGE_ID` column, and the concept list has example forms prefixed with language ID.

**Comment by fmatter** [comment]
Yes, this works perfectly with both of my multilingual example databases!

**Comment by xrotwang** [comment]
@fmatter I included a small portion of your example dataset in the test suite. Do you think this is fine, or should I alter the data?

**Comment by fmatter** [comment]
> @fmatter I included a small portion of your example dataset in the test suite. Do you think this is fine, or should I alter the data?

Actually, yes… these contain some preliminary analyses and wrong transcriptions. I suggest you use this one instead: [igt_sample.zip](https://github.com/cldf/pyigt/files/4532615/igt_sample.zip). All of these are already [online at my Cariban database](http://cariban-morphology.herokuapp.com/examples).

**Comment by xrotwang** [comment]
ok. will do.

**Pull request merged**
